# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/linaro/projects/Minion

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/linaro/projects/Minion

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linaro/projects/Minion/CMakeFiles /home/linaro/projects/Minion/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linaro/projects/Minion/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Minion

# Build rule for target.
Minion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Minion
.PHONY : Minion

# fast build rule for target.
Minion/fast:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/build
.PHONY : Minion/fast

Client.o: Client.cpp.o
.PHONY : Client.o

# target to build an object file
Client.cpp.o:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/Client.cpp.o
.PHONY : Client.cpp.o

Client.i: Client.cpp.i
.PHONY : Client.i

# target to preprocess a source file
Client.cpp.i:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/Client.cpp.i
.PHONY : Client.cpp.i

Client.s: Client.cpp.s
.PHONY : Client.s

# target to generate assembly for a file
Client.cpp.s:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/Client.cpp.s
.PHONY : Client.cpp.s

Lidar.o: Lidar.cpp.o
.PHONY : Lidar.o

# target to build an object file
Lidar.cpp.o:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/Lidar.cpp.o
.PHONY : Lidar.cpp.o

Lidar.i: Lidar.cpp.i
.PHONY : Lidar.i

# target to preprocess a source file
Lidar.cpp.i:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/Lidar.cpp.i
.PHONY : Lidar.cpp.i

Lidar.s: Lidar.cpp.s
.PHONY : Lidar.s

# target to generate assembly for a file
Lidar.cpp.s:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/Lidar.cpp.s
.PHONY : Lidar.cpp.s

SerialPort.o: SerialPort.cpp.o
.PHONY : SerialPort.o

# target to build an object file
SerialPort.cpp.o:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/SerialPort.cpp.o
.PHONY : SerialPort.cpp.o

SerialPort.i: SerialPort.cpp.i
.PHONY : SerialPort.i

# target to preprocess a source file
SerialPort.cpp.i:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/SerialPort.cpp.i
.PHONY : SerialPort.cpp.i

SerialPort.s: SerialPort.cpp.s
.PHONY : SerialPort.s

# target to generate assembly for a file
SerialPort.cpp.s:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/SerialPort.cpp.s
.PHONY : SerialPort.cpp.s

Server.o: Server.cpp.o
.PHONY : Server.o

# target to build an object file
Server.cpp.o:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/Server.cpp.o
.PHONY : Server.cpp.o

Server.i: Server.cpp.i
.PHONY : Server.i

# target to preprocess a source file
Server.cpp.i:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/Server.cpp.i
.PHONY : Server.cpp.i

Server.s: Server.cpp.s
.PHONY : Server.s

# target to generate assembly for a file
Server.cpp.s:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/Server.cpp.s
.PHONY : Server.cpp.s

Spark.o: Spark.cpp.o
.PHONY : Spark.o

# target to build an object file
Spark.cpp.o:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/Spark.cpp.o
.PHONY : Spark.cpp.o

Spark.i: Spark.cpp.i
.PHONY : Spark.i

# target to preprocess a source file
Spark.cpp.i:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/Spark.cpp.i
.PHONY : Spark.cpp.i

Spark.s: Spark.cpp.s
.PHONY : Spark.s

# target to generate assembly for a file
Spark.cpp.s:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/Spark.cpp.s
.PHONY : Spark.cpp.s

Video.o: Video.cpp.o
.PHONY : Video.o

# target to build an object file
Video.cpp.o:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/Video.cpp.o
.PHONY : Video.cpp.o

Video.i: Video.cpp.i
.PHONY : Video.i

# target to preprocess a source file
Video.cpp.i:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/Video.cpp.i
.PHONY : Video.cpp.i

Video.s: Video.cpp.s
.PHONY : Video.s

# target to generate assembly for a file
Video.cpp.s:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/Video.cpp.s
.PHONY : Video.cpp.s

gameObject.o: gameObject.cpp.o
.PHONY : gameObject.o

# target to build an object file
gameObject.cpp.o:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/gameObject.cpp.o
.PHONY : gameObject.cpp.o

gameObject.i: gameObject.cpp.i
.PHONY : gameObject.i

# target to preprocess a source file
gameObject.cpp.i:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/gameObject.cpp.i
.PHONY : gameObject.cpp.i

gameObject.s: gameObject.cpp.s
.PHONY : gameObject.s

# target to generate assembly for a file
gameObject.cpp.s:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/gameObject.cpp.s
.PHONY : gameObject.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/main.cpp.s
.PHONY : main.cpp.s

robotControl.o: robotControl.cpp.o
.PHONY : robotControl.o

# target to build an object file
robotControl.cpp.o:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/robotControl.cpp.o
.PHONY : robotControl.cpp.o

robotControl.i: robotControl.cpp.i
.PHONY : robotControl.i

# target to preprocess a source file
robotControl.cpp.i:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/robotControl.cpp.i
.PHONY : robotControl.cpp.i

robotControl.s: robotControl.cpp.s
.PHONY : robotControl.s

# target to generate assembly for a file
robotControl.cpp.s:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/robotControl.cpp.s
.PHONY : robotControl.cpp.s

wrapper.o: wrapper.cpp.o
.PHONY : wrapper.o

# target to build an object file
wrapper.cpp.o:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/wrapper.cpp.o
.PHONY : wrapper.cpp.o

wrapper.i: wrapper.cpp.i
.PHONY : wrapper.i

# target to preprocess a source file
wrapper.cpp.i:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/wrapper.cpp.i
.PHONY : wrapper.cpp.i

wrapper.s: wrapper.cpp.s
.PHONY : wrapper.s

# target to generate assembly for a file
wrapper.cpp.s:
	$(MAKE) -f CMakeFiles/Minion.dir/build.make CMakeFiles/Minion.dir/wrapper.cpp.s
.PHONY : wrapper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Minion"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Client.o"
	@echo "... Client.i"
	@echo "... Client.s"
	@echo "... Lidar.o"
	@echo "... Lidar.i"
	@echo "... Lidar.s"
	@echo "... SerialPort.o"
	@echo "... SerialPort.i"
	@echo "... SerialPort.s"
	@echo "... Server.o"
	@echo "... Server.i"
	@echo "... Server.s"
	@echo "... Spark.o"
	@echo "... Spark.i"
	@echo "... Spark.s"
	@echo "... Video.o"
	@echo "... Video.i"
	@echo "... Video.s"
	@echo "... gameObject.o"
	@echo "... gameObject.i"
	@echo "... gameObject.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... robotControl.o"
	@echo "... robotControl.i"
	@echo "... robotControl.s"
	@echo "... wrapper.o"
	@echo "... wrapper.i"
	@echo "... wrapper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

